### ISSUE TITLE
flipped coordinates

### ISSUE THREAD

**Issue by sscheidt77** [lvauvillier/dji-log-parser#13]
I did an export of a DJI encrypted flight log, which was flown in Iceland. The latitude and longitude coordinates were flipped in the KML file. 

For example, the coordinates should be 65 deg latitude, and -16 deg longitude. 
The KML file is placed at the coordinates of -16 deg latitude, and 65 deg longitude. 

Can this error be corrected quickly?

Thanks for development of this tool. I'm eager to see it's results.

**Comment by sscheidt77** [comment]
![image](https://github.com/user-attachments/assets/a3214d48-720c-41b9-a10f-ac48397c5c0e)

**Comment by lvauvillier** [comment]
Good catch. Fixed. Thanks a lot!

**Comment by sscheidt77** [comment]
You're welcome! My first "catch" on code in github.
