### ISSUE TITLE
camera.is_video value is Incomplete parsing 

### ISSUE THREAD

**Issue by windcatcher** [lvauvillier/dji-log-parser#14]
when i export to csv file,i find that camera.is_video value is Incomplete parsing

**Comment by windcatcher** [comment]
When I exported the csv file, I found that the camera.is_video value was incorrectly parsed, and part of the time when video recording had started, the value of is_video was still false.

**Comment by lvauvillier** [comment]
Hi @windcatcher thanks for raising this issue. Could you please share the log file so I can take a closer look and investigate what's happening?

**Comment by windcatcher** [comment]
[log1.txt](https://github.com/user-attachments/files/17469456/log1.txt)
here is the log file. @lvauvillier

**Comment by lvauvillier** [comment]
Fixed! Thanks a lot @windcatcher.
