### ISSUE TITLE
Unable to parse file: InfoParseError("invalid utf-8 sequence of 1 bytes from index 8 at 0x12e")

### ISSUE THREAD

**Issue by MAVProxyUser** [lvauvillier/dji-log-parser#2]
Unable to parse file: InfoParseError("invalid utf-8 sequence of 1 bytes from index 0 at 0x138")
Unable to parse file: InfoParseError("invalid utf-8 sequence of 1 bytes from index 15 at 0x14")
Unable to parse file: InfoParseError("invalid utf-8 sequence of 1 bytes from index 8 at 0x12e")

from: thread 'main' panicked at src/main.rs:41:45:

Any idea what causes this?

**Comment by lvauvillier** [comment]
Hi @MAVProxyUser can you share your log file?

**Comment by MAVProxyUser** [comment]
https://archive.org/download/FlightLogs

**Comment by lvauvillier** [comment]
Thanks @MAVProxyUser. However, these do not looks like to be the standard .txt logs from DJI.

**Comment by MAVProxyUser** [comment]
you have to extract them... 
gzip -d FlightLogs.z01.gz   (it would not upload with out being gzipped)
Then use any zip program that can handle a multi file archive. 
Open  FlightLogs.zip, and it should span all the other z01, z02, z03, etc files automatically and extract a huge pile of 
.txt.zip files. (35 gig worth)

You can recursively extract them all to normal .txt files after stripping the gzip compression (not really .zip files even though that it their extension) 

find . -name "*.zip" -exec pigz -d -z -v {} \;

You should be left with gigs worth of plain txt DJI log files. 

Hope that helps.

**Comment by MAVProxyUser** [comment]
@lvauvillier there is at least one log per folder that exhibits the error. You should have a huge sample set.

**Comment by lvauvillier** [comment]
@MAVProxyUser I'm currently unable to download the entire archive due to limited bandwidth. Could you please send just one .txt log file that produice the error?

**Comment by lvauvillier** [comment]
Fixed.Thanks for reporting this.
