### ISSUE TITLE
EXIF lat / lon fields incorrect? 

### ISSUE THREAD

**Issue by MAVProxyUser** [lvauvillier/dji-log-parser#6]
Looks like the Longitude field is borked? 

![image](https://github.com/lvauvillier/dji-log-parser/assets/2904396/cef964e3-5a2a-4541-9478-9fb0448ec613)

![image](https://github.com/lvauvillier/dji-log-parser/assets/2904396/2115a596-c664-4b8a-8ba0-fe57fb0480f6)

You can spot check with https://exifinfo.org, or on my Mac this shows up on the file info screen.

**Comment by MAVProxyUser** [comment]
Is is possible to add SN, and file path to the EXIF data too? (to make it easier to match up photos with their owners later)

**Comment by lvauvillier** [comment]
Yes i noticed this too. I checked several logs and the value of longitude / moment_pic_longitude was 0 in the info section, so i can't fix it as this is the recorded info. Can you check on your side if this is the case too?

A workaround can be to use the first point of the track.

**Comment by lvauvillier** [comment]
Ok, my lat/lng to DMS conversion didn't work for negative values. Fix in progress.

**Comment by MAVProxyUser** [comment]
Excellent I was just logging back in to check. I did notice some seemed fine.  Will git pull and try again! 
![image](https://github.com/lvauvillier/dji-log-parser/assets/2904396/69d15974-07f9-484b-9b1c-72ac934fdb9e)

**Comment by MAVProxyUser** [comment]
@lvauvillier it seemed to chew through almost all of the dataset. There were a few crashes at the end of the run. I'll have to pinpoint the file names again. Here is the crash if it is useful to you: 

```
thread 'main' panicked at dji-log-parser/src/lib.rs:208:59:
range start index 398220 out of range for slice of length 261632
stack backtrace:
   0:     0x560b0122bebb - std::backtrace_rs::backtrace::libunwind::trace::h3926e05c1d1f3b6d
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:     0x560b0122bebb - std::backtrace_rs::backtrace::trace_unsynchronized::h9f5691494ac25ae6
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560b0122bebb - std::sys_common::backtrace::_print_fmt::h7e6bb7b81bf214f4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x560b0122bebb - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcf688c88e28c91b4
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x560b01261d80 - core::fmt::rt::Argument::fmt::h59a542682908b618
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/rt.rs:142:9
   5:     0x560b01261d80 - core::fmt::write::hce91e70849a27dee
                               at /build/rustc-60UC9b/rustc-1.75.0+dfsg0ubuntu1~bpo0/library/core/src/fmt/mod.rs:1120:17
   6:     0x560b01220fed - std::io::Write::write_fmt::h0bba58d3b1b495e9

```

**Comment by lvauvillier** [comment]
Thanks @MAVProxyUser. It seems like the pointer for the info section is outside the file itself. I'd appreciate having the file name to take a look.
