### ISSUE TITLE
I can't decode some logs

### ISSUE THREAD

**Issue by camargoz** [lvauvillier/dji-log-parser#9]
When testing version 0.4.0 I was unable to decode some logs, this log is also not possible to be decoded by DJI's ParserLib.

NOTE: When I try to decode this log, the decoding process does not timeout.

Drone Model: DJI Mavic 2 Pro / Interprise
LOG creation date: 2020-07-23

**Comment by lvauvillier** [comment]
Hi @camargoz, can you share the log file? I'll take a look.

**Comment by camargoz** [comment]
@lvauvillier  Do you have any private contact form where I can send the LOG file?

**Comment by lvauvillier** [comment]
@camargoz you will find my email in the author section of this file :)
https://github.com/lvauvillier/dji-log-parser/blob/master/Cargo.toml

**Comment by camargoz** [comment]
I sended the LOG for your e-mail.

**Comment by camargoz** [comment]
I believe that at some point when I tried to decode by passing the response to a json ("> records.json") it didn't work correctly and I got this error, but it was resolved!

NOTE: I removed the previously generated file and tried again.

CLI: ./dji-log ~/Downloads/DJIFlightRecord_2020-07-23_[10-01-46].txt --api-key __API_KEY__ > records.json

**Comment by camargoz** [comment]
Very interesting, if you need help with the availability of some logs or anything else, you can get in touch.

Mathews Camargo

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
